# Generated by Django 4.1.3 on 2023-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('Все', 'Все'), ('Колорист', 'Колорист'), ('Парикмахер', 'Парикмахер'), ('Визажист', 'Визажист'), ('Маникюр', 'Маникюр')], max_length=15, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='chose_location',
            field=models.CharField(blank=True, choices=[('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург'), ('Новосибирск', 'Новосибирск')], max_length=255, null=True, verbose_name='Выбрана локация'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='chose_sphere',
            field=models.CharField(blank=True, choices=[('Все', 'Все'), ('Колорист', 'Колорист'), ('Парикмахер', 'Парикмахер'), ('Визажист', 'Визажист'), ('Маникюр', 'Маникюр')], max_length=255, null=True, verbose_name='Выбрана сфера'),
        ),
    ]
