# Generated by Django 4.1.3 on 2023-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0002_alter_location_options_alter_location_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='chose_location',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург'), ('Новосибирск', 'Новосибирск')], default='Москва', max_length=255, verbose_name='Выбрана локация'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='chose_sphere',
            field=models.CharField(choices=[('Все', 'Все'), ('Колорист', 'Колорист'), ('Парикмахер', 'Парикмахер'), ('Визажист', 'Визажист'), ('Маникюр', 'Маникюр')], default='Все', max_length=255, verbose_name='Выбрана сфера'),
        ),
    ]
