# Generated by Django 4.1.3 on 2023-08-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0003_alter_telegramusers_chose_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='location_photos/')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='photos',
            field=models.ManyToManyField(blank=True, to='master_locations.photo', verbose_name='Изображения'),
        ),
    ]
