# Generated by Django 4.1.3 on 2023-08-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0005_alter_photo_options_alter_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
