# Generated by Django 4.1.3 on 2023-08-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0006_location_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusers',
            name='bot_activation_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во активаций'),
        ),
    ]
