# Generated by Django 4.1.3 on 2023-08-21 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0007_telegramusers_bot_activation_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramusers',
            name='chose_price',
        ),
        migrations.RemoveField(
            model_name='telegramusers',
            name='chose_sphere',
        ),
    ]
