# Generated by Django 4.1.3 on 2023-08-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0008_remove_telegramusers_chose_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
