# Generated by Django 4.1.3 on 2023-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0009_alter_telegramusers_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Название фотографии'),
        ),
    ]
