# Generated by Django 4.1.3 on 2023-08-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0011_location_contact_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='emodji',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Emodji :)'),
        ),
    ]
