# Generated by Django 4.1.3 on 2023-08-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0012_location_emodji'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationVisitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.IntegerField(default=0, verbose_name='Переходов')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_locations.location', verbose_name='Локация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_locations.telegramusers', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика локаций',
                'verbose_name_plural': 'Статистика локаций',
            },
        ),
    ]
