# Generated by Django 4.1.3 on 2023-08-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0013_locationvisitstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(blank=True, choices=[('Все', 'Все'), ('Колорист', 'Колорист'), ('Парикмахер', 'Парикмахер'), ('Визажист', 'Визажист'), ('Маникюр', 'Маникюр')], default=None, max_length=15, null=True, verbose_name='Категория'),
        ),
    ]
