# Generated by Django 4.1.3 on 2023-08-29 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0014_alter_location_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='photos',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
