# Generated by Django 4.2.4 on 2023-09-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0015_remove_location_photos_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotActivationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activation', models.DateField(verbose_name='Дата')),
                ('activation_count', models.IntegerField(default=0, verbose_name='Кол-во активаций')),
            ],
            options={
                'verbose_name': 'Статистика активаций',
                'verbose_name_plural': 'Статистика активаций',
            },
        ),
    ]
