# Generated by Django 4.1.3 on 2023-11-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0017_rename_botactivationstats_botactivationstat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('Все', 'Все'), ('Колорист', 'Колорист'), ('Парикмахер', 'Парикмахер'), ('Маникюр', 'Маникюр'), ('Визажист', 'Визажист')], default='Все', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='location',
            name='contact_link',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Контактная ссылка'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='telegramusers',
            name='chose_location',
            field=models.CharField(choices=[('Москва', 'Москва'), ('Новосибирск', 'Новосибирск'), ('Санкт-Петербург', 'Санкт-Петербург')], default='Москва', max_length=15, verbose_name='Выбрана локация'),
        ),
    ]
