# Generated by Django 4.1.3 on 2023-11-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0018_alter_location_options_alter_location_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=720, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='location',
            name='short_description',
            field=models.CharField(max_length=256, verbose_name='Краткое описание (для карты)'),
        ),
    ]
