# Generated by Django 4.1.3 on 2024-03-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0020_alter_location_contact_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='full_address',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Полный адрес'),
        ),
    ]
