# Generated by Django 4.1.3 on 2024-03-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0021_location_full_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=256, verbose_name='Марка')),
                ('model', models.CharField(max_length=256, verbose_name='Модель')),
                ('equipment', models.CharField(max_length=256, verbose_name='Комплектация')),
                ('year_of_issue', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('class_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Класс')),
                ('color', models.CharField(blank=True, max_length=256, null=True, verbose_name='Цвет')),
                ('body', models.CharField(blank=True, max_length=256, null=True, verbose_name='Кузов')),
                ('drive_unit', models.CharField(blank=True, max_length=256, null=True, verbose_name='Привод')),
                ('fuel_type', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип топлива')),
                ('transmission', models.CharField(blank=True, max_length=256, null=True, verbose_name='Коробка передач')),
                ('power', models.IntegerField(blank=True, null=True, verbose_name='Мощность л.с.')),
                ('volume_engine', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Объем двигателя')),
                ('fuel_volume', models.IntegerField(blank=True, null=True, verbose_name='Объем топлива')),
                ('acceleration_to100', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Разгон до 100')),
                ('seats_number', models.IntegerField(blank=True, null=True, verbose_name='Кол-во посадочных мест')),
                ('city', models.CharField(blank=True, max_length=256, null=True, verbose_name='Город')),
                ('rent_cost_per_day', models.DecimalField(blank=True, decimal_places=8, max_digits=8, null=True, verbose_name='Стоимость аренды 1-2 суток')),
                ('rent_cost_per_month', models.DecimalField(blank=True, decimal_places=8, max_digits=8, null=True, verbose_name='Стоимость аренды 30+ дней')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('links', models.TextField(blank=True, null=True, verbose_name='Ссылки на авто')),
            ],
            options={
                'verbose_name': 'Авто',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
