# Generated by Django 4.1.3 on 2024-05-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_locations', '0024_location_price_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='price_number',
            field=models.FloatField(default=0, max_length=25, verbose_name='Цена (Число)'),
        ),
    ]
